services:
  - redis@arch.service
notify:
  slack:
    webhook_url: webhook_url
    channel:     channel
    on_active:   true
    on_failed:   true
    on_restart:  true
  hipchat:
    room:  hipchatRoom
    token: hipchatToken
    on_active:  true
    on_failed:  true
    on_restart: true
