services:
  - redis@arch.service
notify:
  slack:
    team:    room
    channel: channel
    token:   token
    on_active:  true
    on_failed:  true
    on_restart: true
  hipchat:
    room:  hipchatRoom
    token: hipchatToken
    on_active:  true
    on_failed:  true
    on_restart: true
